export const GET_DIVISION_REQUEST ="GET_DIVISION_REQUEST"
export const GET_DIVISION_SUCCESSS ="GET_DIVISION_SUCCESSS"
export const GET_DIVISION_FAIL ="GET_DIVISION_FAIL"  

export const GET_ALL_DIVISION_REQUEST ="GET_ALL_DIVISION_REQUEST"
export const GET_ALL_DIVISION_SUCCESSS ="GET_ALL_DIVISION_SUCCESSS"
export const GET_ALL_DIVISION_FAIL ="GET_ALL_DIVISION_FAIL"  

export const UPDATE_DIVISION_REQUEST ="UPDATE_DIVISION_REQUEST"
export const UPDATE_DIVISION_SUCCESS ="UPDATE_DIVISION_SUCCESS"
export const UPDATE_DIVISION_FAIL ="UPDATE_DIVISION_FAIL" 

export const GET_DIVISION_BY_REQUEST ="GET_DIVISION_BY_REQUEST"
export const GET_DIVISION_BY_SUCCESS ="GET_DIVISION_BY_SUCCESS"
export const GET_DIVISION_BY_FAIL ="GET_DIVISION_BY_FAIL" 

export const FIND_DIVISION_BY_DATA_AND_UPDATE_REQUEST ="FIND_DIVISION_BY_DATA_AND_UPDATE_REQUEST"
export const FIND_DIVISION_BY_DATA_AND_UPDATE_SUCCESS ="FIND_DIVISION_BY_DATA_AND_UPDATE_SUCCESS"
export const FIND_DIVISION_BY_DATA_AND_UPDATE_FAIL ="FIND_DIVISION_BY_DATA_AND_UPDATE_FAIL" 

export const FIND_DIVISION_BY_ID_AND_UPDATE_ENnUMBER_REQUEST ="FIND_DIVISION_BY_ID_AND_UPDATE_ENnUMBER_REQUEST"
export const FIND_DIVISION_BY_ID_AND_UPDATE_ENnUMBER_SUCCESS ="FIND_DIVISION_BY_ID_AND_UPDATE_ENnUMBER_SUCCESS"
export const FIND_DIVISION_BY_ID_AND_UPDATE_ENnUMBER_FAIL ="FIND_DIVISION_BY_ID_AND_UPDATE_ENnUMBER_FAIL" 

export const DELETE_DIVISION_REQUEST ="DELETE_DIVISION_REQUEST"
export const DELETE_DIVISION_SUCCESS ="DELETE_DIVISION_SUCCESS"
export const DELETE_DIVISION_FAIL ="DELETE_DIVISION_FAIL" 

export const GET_DIVISION_ID ="GET_DIVISION_ID" 
export const SET_UPDATE_VAL ="SET_UPDATE_VAL" 

export const STORE_DIVISION_DATA ="STORE_DIVISION_DATA" 
export const CLEARE_DIVISION_DATA ="CLEARE_DIVISION_DATA" 


export const CLEAR_ERRORS ="CLEAR_ERRORS"