export const CREATE_LECTURE_REQUEST ="CREATE_LECTURE_REQUEST"
export const CREATE_LECTURE_SUCCESS ="CREATE_LECTURE_SUCCESS"
export const CREATE_LECTURE_FAIL ="CREATE_LECTURE_FAIL" 

export const GET_ALL_LECTURE_REQUEST ="GET_ALL_LECTURE_REQUEST"
export const GET_ALL_LECTURE_SUCCESS ="GET_ALL_LECTURE_SUCCESS"
export const GET_ALL_LECTURE_FAIL ="GET_ALL_LECTURE_FAIL" 

export const PUSH_ID_AND_UPDATE_REQUEST ="PUSH_ID_AND_UPDATE_REQUEST"
export const PUSH_ID_AND_UPDATE_SUCCESS ="PUSH_ID_AND_UPDATE_SUCCESS"
export const PUSH_ID_AND_UPDATE_FAIL ="PUSH_ID_AND_UPDATE_FAIL"

export const DELETE_LECUTURE_REQUEST ="DELETE_LECUTURE_REQUEST"
export const DELETE_LECUTURE_SUCCESS ="DELETE_LECUTURE_SUCCESS"
export const DELETE_LECUTURE_FAIL ="DELETE_LECUTURE_FAIL" 


export const GET_LECUTURE_BY_DIVISION_ID_REQUEST ="GET_LECUTURE_BY_DIVISION_ID_REQUEST"
export const GET_LECUTURE_BY_DIVISION_ID_SUCCESS ="GET_LECUTURE_BY_DIVISION_ID_SUCCESS"
export const GET_LECUTURE_BY_DIVISION_ID_FAIL ="GET_LECUTURE_BY_DIVISION_ID_FAIL" 

export const GET_LECUTURE_BY_ID_AND_REPLACE_PRESENTY_ARRAY_REQUEST ="GET_LECUTURE_BY_ID_AND_REPLACE_PRESENTY_ARRAY_REQUEST"
export const GET_LECUTURE_BY_ID_AND_REPLACE_PRESENTY_ARRAY_SUCCESS ="GET_LECUTURE_BY_ID_AND_REPLACE_PRESENTY_ARRAY_SUCCESS"
export const GET_LECUTURE_BY_ID_AND_REPLACE_PRESENTY_ARRAY_FAIL ="GET_LECUTURE_BY_ID_AND_REPLACE_PRESENTY_ARRAY_FAIL" 


export const CLEAR_ERRORS ="CLEAR_ERRORS"