
export const UPDATE_TIME_TABLE_REQUEST ="UPDATE_TIME_TABLE_REQUEST"
export const UPDATE_TIME_TABLE_SUCCESS ="UPDATE_TIME_TABLE_SUCCESS"
export const UPDATE_TIME_TABLE_FAIL ="UPDATE_TIME_TABLE_FAIL" 

export const CREATE_TIME_TABLE_REQUEST ="CREATE_TIME_TABLE_REQUEST"
export const CREATE_TIME_TABLE_SUCCESS ="CREATE_TIME_TABLE_SUCCESS"
export const CREATE_TIME_TABLE_FAIL ="CREATE_TIME_TABLE_FAIL" 

export const GET_TIME_TABLE_BY_ID_REQUEST ="GET_TIME_TABLE_BY_ID_REQUEST"
export const GET_TIME_TABLE_BY_ID_SUCCESS ="GET_TIME_TABLE_BY_ID_SUCCESS"
export const GET_TIME_TABLE_BY_ID_FAIL ="GET_TIME_TABLE_BY_ID_FAIL" 

export const SET_TIME_TABLE_DATA ="SET_TIME_TABLE_DATA" 

export const CLEARE_TIMRTABLE_DATA ="CLEARE_TIMRTABLE_DATA" 

export const CLEAR_ERRORS ="CLEAR_ERRORS"
