export const GET_USER_DETAIL_REQUEST ="GET_USER_DETAIL_REQUEST"
export const GET_USER_DETAIL_SUCCESSS ="GET_USER_DETAIL_SUCCESSS"
export const GET_USER_DETAIL_FAIL ="GET_USER_DETAIL_FAIL"  

export const UPDATE_USER_DETAIL_REQUEST ="UPDATE_USER_DETAIL_REQUEST"
export const UPDATE_USER_DETAIL_SUCCESS ="UPDATE_USER_DETAIL_SUCCESS"
export const UPDATE_USER_DETAIL_FAIL ="UPDATE_USER_DETAIL_FAIL" 

export const GET_ALL_USER_DETAIL_REQUEST ="GET_ALL_USER_DETAIL_REQUEST"
export const GET_ALL_USER_DETAIL_SUCCESS ="GET_ALL_USER_DETAIL_SUCCESS"
export const GET_ALL_USER_DETAIL_FAIL ="GET_ALL_USER_DETAIL_FAIL" 


export const GET_ALL_USER_DETAIL_BY_DATA_REQUEST ="GET_ALL_USER_DETAIL_BY_DATA_REQUEST"
export const GET_ALL_USER_DETAIL_BY_DATA_SUCCESS ="GET_ALL_USER_DETAIL_BY_DATA_SUCCESS"
export const GET_ALL_USER_DETAIL_BY_DATA_FAIL ="GET_ALL_USER_DETAIL_BY_DATA_FAIL" 

export const SET_USER_DETAIL_TO_VIEW_ACCOUNT ="SET_USER_DETAIL_TO_VIEW_ACCOUNT"

export const GET_USER_DETAIL_copy_REQUEST ="GET_USER_DETAIL_copy_REQUEST"
export const GET_USER_DETAIL_copy_SUCCESSS ="GET_USER_DETAIL_copy_SUCCESSS"
export const GET_USER_DETAIL_copy_FAIL ="GET_USER_DETAIL_copy_FAIL"  

export const FIND_USERDETAIL_BY_ID_UPDATE_ROLE_REQUEST ="FIND_USERDETAIL_BY_ID_UPDATE_ROLE_REQUEST"
export const FIND_USERDETAIL_BY_ID_UPDATE_ROLE_SUCCESSS ="FIND_USERDETAIL_BY_ID_UPDATE_ROLE_SUCCESSS"
export const FIND_USERDETAIL_BY_ID_UPDATE_ROLE_FAIL ="FIND_USERDETAIL_BY_ID_UPDATE_ROLE_FAIL"  

export const UPDATE_LOCAL_DATA ="UPDATE_LOCAL_DATA"  

export const CLEAR_ERRORS ="CLEAR_ERRORS"